=begin

Model to map to table in Banner

column names

SZVEDSD_ID
SZVEDSD_LAST_NAME
SZVEDSD_FIRST_NAME
SZVEDSD_MIDDLE_NAME
SZVEDSD_ENROLL_STAT
SZVEDSD_CLASSIFICATION
SZVEDSD_WITHDRAWALS
SZVEDSD_TERM_GRADUATED
SZVEDSD_GENDER
SZVEDSD_SSN
SZVEDSD_DOB
SZVEDSD_RACE
SZVEDSD_HISPANIC
SZVEDSD_STATE
SZVEDSD_COUNTY
SZVEDSD_CITIZENSHIP
SZVEDSD_COUNTRY_ORIGIN
SZVEDSD_ESL
SZVEDSD_COMPUTER_TOEFL
SZVEDSD_TOEFL
SZVEDSD_TOEFL_ESSAY
SZVEDSD_TOEFL_LISTENING
SZVEDSD_TOEFL_READING
SZVEDSD_TOEFL_SPEAKING
SZVEDSD_TOEFL_STRUCT_WRITING
SZVEDSD_TOEFL_TOTAL
SZVEDSD_TOEFL_WRITING
SZVEDSD_TEST_WRITTEN_ENGLISH
SZVEDSD_IELTS_LISTENING
SZVEDSD_IELTS_READING
SZVEDSD_IELTS_WRITING
SZVEDSD_IELTS_SPEAKING
SZVEDSD_IELTS_BAND_SCORE
SZVEDSD_TRANSFER_STUDENT
SZVEDSD_TERM_EDS_EXPLOR_MJR
SZVEDSD_TERM_DECLARED_EDS_MJR
SZVEDSD_PRIMARY_MAJOR
SZVEDSD_PRIMARY_MAJOR_CONC
SZVEDSD_SECONDARY_MAJOR
SZVEDSD_SECONDARY_MAJOR_CONC
SZVEDSD_ADVISOR
SZVEDSD_HIGH_SCHOOL_GPA UMBER
SZVEDSD_HIGH_SCHOLL_RANK UMBER
SZVEDSD_ACT_ENGLISH
SZVEDSD_ACT_MATH
SZVEDSD_ACT_READING
SZVEDSD_ACT_SCIENCE_REASONING
SZVEDSD_ACT_COMPOSITE
SZVEDSD_SAT_VERB_CRIT_READING
SZVEDSD_SAT_MATH
SZVEDSD_SAT_WRITING
SZVEDSD_TERM_TAKEN
SZVEDSD_CRN
SZVEDSD_COURSE
SZVEDSD_GRADE
SZVEDSD_REGISTRATION_STAT
SZVEDSD_CREDITS_ATTEMPTED
SZVEDSD_CREDITS_EARNED
SZVEDSD_MINORS
SZVEDSD_GPA_IND
SZVEDSD_EMAIL
SZVEDSD_CPO
SZVEDSD_FILTER_TERM
SAVEDSD_INSTRUCTOR

=end

if Rails.env == 'production'
  
  class Banner < ApplicationRecord
    
    establish_connection :banner 
    self.table_name = "saturn.szvedsd"
    
    scope :by_term, ->(term) {where :SZVEDSD_FILTER_TERM => term}
    scope :by_ssn, ->(ssn) {find_by :SZVEDSD_SSN => ssn}
    
  end
end
